name: PostgreSQL Service Example
on: push

env:
 CONNECTION_STRING: postgres://postgres:postgres@localhost:5432/dvdrental

jobs:
  runner-job:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install postgresql-client
          sudo systemctl start postgresql

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Restore test database
        run: |
          createdb postgres://postgres:postgres@localhost:5432/dvdrental
          pg_restore -c -U postgres -d $CONNECTION_STRING ./tests/dvdrental.tar

      - name: Connect to PostgreSQL
        run: yarn test
        env:
          CONNECTION_STRING: $CONNECTION_STRING
